//! [`Column<L>`]: a strongly-typed, validated, zero-copy view of one record batch column.
//!
//! A column has a name and metadata; a [`TypedArray`], its data half, has
//! neither.
//!
//! The wrapper validates the arrow array **once, eagerly** at construction
//! (exact data type, including the inner types of nested arrays, plus nulls at
//! every non-`Option` nesting level). After that, element access is infallible,
//! fully typed, and zero-copy.

use std::{collections::BTreeMap, sync::Arc};

use arrow::array::ArrayRef;
use arrow::datatypes::{DataType, Field};

use crate::data_type::{InfallibleBuild, PrimitiveType, RefType};
use crate::typed_array::{TypedArray, TypedArrayIntoIter, TypedArrayIter};
use crate::{ColumnError, Error, ErrorKind, LogicalType};

/// A strongly-typed, validated, zero-copy view of one record batch column.
///
/// The logical type `L` describes the exact data type and nullability,
/// e.g. `Column<List<Utf8>>` or `Column<Option<i64>>`.
///
/// # Relationship to the other main types
/// A column is a [`TypedArray<L>`](TypedArray) (the validated array, and every
/// method for reading it) plus the two things that live on the arrow [`Field`]:
/// the column's [`name`](Column::name) and its
/// [`metadata`](Column::metadata). Every constructor therefore takes a name.
///
/// Use a [`TypedArray`] instead for an array that isn't a record batch column,
/// and so has neither — that is the type with the `Default`, `From<Vec<_>>`,
/// `FromIterator`, and `TryFrom<ArrayRef>` impls, none of which can name a
/// column. Convert either way with [`Column::new`],
/// [`as_typed_array`](Column::as_typed_array), and
/// [`into_typed_array`](Column::into_typed_array).
///
/// Getting a column out of a record batch is
/// [`Column::from_record_batch_and_name`], or a
/// [`ColumnDesc`](crate::ColumnDesc) — generated by `#[derive(Quiver)]`, or
/// declared by you — which holds the name and `L` so the call site needs
/// neither.
pub struct Column<L: LogicalType> {
    /// The data: the arrow array plus its downcast view.
    array: TypedArray<L>,

    /// The name of the column, stored on the arrow
    /// [`arrow::datatypes::Field`] when converting to/from a record batch.
    name: Arc<String>,

    /// Per-column metadata, stored on the arrow [`arrow::datatypes::Field`]
    /// when converting to/from a record batch.
    metadata: Arc<BTreeMap<String, String>>,
}

impl<L: LogicalType> Column<L> {
    /// May the values of this column be null?
    pub const NULLABLE: bool = L::NULLABLE;

    /// Names an already-validated [`TypedArray`], making it a column.
    ///
    /// The counterpart of [`into_typed_array`](Column::into_typed_array), and
    /// the cheapest way in: nothing is validated or copied, since a
    /// [`TypedArray`] is validated already.
    #[must_use]
    pub fn new(name: impl Into<String>, array: TypedArray<L>) -> Self {
        Self {
            array,
            name: Arc::new(name.into()),
            metadata: Arc::default(),
        }
    }

    /// Validates the array against the logical type `L` (data type and nullability,
    /// recursively), then downcasts it (zero-copy), under the column name `name`.
    ///
    /// # Errors
    /// Errors on data type mismatch, or on nulls at any non-`Option` nesting level.
    pub fn try_new(name: impl Into<String>, array: ArrayRef) -> Result<Self, ColumnError> {
        Ok(Self::new(name, TypedArray::try_new(array)?))
    }

    /// Extracts and validates a single column of a record batch, by name.
    ///
    /// Looks up the column by name (returning [`ErrorKind::MissingColumn`] if it
    /// is absent), validates it against `L` (data type and nullability, recursively),
    /// and carries over the arrow [`Field`] metadata.
    ///
    /// This is the no-derive equivalent of the `COLUMN_*` descriptors that
    /// `#[derive(Quiver)]` generates; prefer those when you have a derived struct,
    /// since they don't hard-code the column name.
    ///
    /// # Errors
    /// Errors if the column is missing, or if it fails validation against `L`.
    pub fn from_record_batch_and_name(
        batch: &arrow::record_batch::RecordBatch,
        name: &str,
    ) -> Result<Self, Error> {
        Self::extract_named(batch, name, "Column")
    }

    /// Shared implementation of [`Column::from_record_batch_and_name`] and the
    /// derive-generated `COLUMN_*` descriptors; `record_type` labels errors.
    pub(crate) fn extract_named(
        batch: &arrow::record_batch::RecordBatch,
        name: &str,
        record_type: &'static str,
    ) -> Result<Self, Error> {
        let (index, field) = batch.schema_ref().column_with_name(name).ok_or_else(|| {
            Error::new(
                record_type,
                ErrorKind::MissingColumn {
                    column: name.to_owned(),
                },
            )
        })?;

        let column = Self::try_new(name, ArrayRef::clone(batch.column(index)))
            .map_err(|err| Error::new(record_type, err.for_column(name.to_owned())))?;

        Ok(column.with_metadata(field.metadata().clone()))
    }

    /// The name of the column, stored on the arrow
    /// [`arrow::datatypes::Field`] when converting to/from a record batch.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// The same column under a different name.
    #[must_use]
    pub fn with_name(mut self, name: impl Into<String>) -> Self {
        self.name = Arc::new(name.into());
        self
    }

    /// Per-column metadata, stored on the arrow [`arrow::datatypes::Field`]
    /// when converting to/from a record batch.
    #[must_use]
    pub fn metadata(&self) -> &BTreeMap<String, String> {
        &self.metadata
    }

    /// Mutable access to the per-column metadata; see [`Column::metadata`].
    ///
    /// The metadata is shared between clones of a column, so this copies it
    /// first if another clone still holds it.
    pub fn metadata_mut(&mut self) -> &mut BTreeMap<String, String> {
        Arc::make_mut(&mut self.metadata)
    }

    /// Replace the per-column metadata.
    ///
    /// Takes anything that iterates key-value pairs, so an arrow
    /// [`HashMap`](std::collections::HashMap), a
    /// [`BTreeMap`], or a plain array of
    /// `&str` pairs all work:
    ///
    /// ```
    /// # use quiver::{Column, Utf8};
    /// let column = Column::<Utf8>::from_values("sensor", ["kitchen"])
    ///     .with_metadata([("unit", "celsius")]);
    /// assert_eq!(column.metadata()["unit"], "celsius");
    /// ```
    #[must_use]
    pub fn with_metadata(
        mut self,
        metadata: impl IntoIterator<Item = (impl Into<String>, impl Into<String>)>,
    ) -> Self {
        self.metadata = Arc::new(
            metadata
                .into_iter()
                .map(|(key, value)| (key.into(), value.into()))
                .collect(),
        );
        self
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.array.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.array.is_empty()
    }

    /// The value at `index`, or `None` if out of bounds.
    ///
    /// See [`Column::value`] for the returned view;
    /// [`Column::get_owned`] returns the owned value instead.
    #[must_use]
    #[inline]
    pub fn get(&self, index: usize) -> Option<L::Value<'_>> {
        self.array.get(index)
    }

    /// The owned value at `index`, or `None` if out of bounds —
    /// e.g. `String` (or your newtype) where [`Column::get`] returns `&str`.
    #[must_use]
    pub fn get_owned(&self, index: usize) -> Option<L::Owned> {
        self.get(index).map(L::to_owned_value)
    }

    /// The value at `index`.
    ///
    /// Works for every logical type, returning the zero-copy view
    /// ([`LogicalType::Value`]): `&str`, `i64`, `Option<…>`, an iterator for
    /// `List<…>`, etc.
    /// Where a plain reference exists in the array — strings, binaries,
    /// primitives (but not `bool`, `Option<…>`, or `List<…>`) — `column[index]`
    /// works too, and is handy with generic code expecting `&T`.
    /// For the owned value (e.g. `String`, or your `newtype_data_type!` type),
    /// see [`Column::value_owned`].
    ///
    /// Panics if out of bounds.
    #[must_use]
    #[inline]
    pub fn value(&self, index: usize) -> L::Value<'_> {
        self.array.value(index)
    }

    /// The owned value at `index` — e.g. `String` (or your newtype)
    /// where [`Column::value`] returns `&str`.
    ///
    /// May allocate (e.g. string columns); for bulk access,
    /// prefer [`Column::iter_owned`] or [`Column::to_vec`].
    ///
    /// Panics if out of bounds.
    #[must_use]
    pub fn value_owned(&self, index: usize) -> L::Owned {
        L::to_owned_value(self.value(index))
    }

    /// Iterates over the zero-copy views ([`LogicalType::Value`]):
    /// `&str`, `i64`, etc — like [`Column::value`], element by element.
    ///
    /// For owned values, see [`Column::iter_owned`].
    #[must_use]
    pub fn iter(&self) -> TypedArrayIter<'_, L> {
        self.array.iter()
    }

    /// Iterates over owned values — e.g. `String` (or your newtype)
    /// where [`Column::iter`] yields `&str`.
    ///
    /// May allocate per element (e.g. string columns).
    pub fn iter_owned(&self) -> impl Iterator<Item = L::Owned> + '_ {
        self.array.iter_owned()
    }

    /// Consumes the column, iterating over owned values — e.g. `String`
    /// (or your newtype) for a `Column<Utf8>`.
    ///
    /// May allocate per element (e.g. string columns); for borrowed views,
    /// iterate `&column` (or call [`Column::iter`]) instead.
    #[must_use]
    pub fn into_iter_owned(self) -> TypedArrayIntoIter<L> {
        self.array.into_iter_owned()
    }

    /// Copies the values into a `Vec` of owned values,
    /// e.g. `Vec<String>` for a `Column<Utf8>`.
    #[must_use]
    pub fn to_vec(&self) -> Vec<L::Owned> {
        self.array.to_vec()
    }

    /// A zero-copy slice of the rows `offset..offset + length`.
    ///
    /// The name and metadata are preserved.
    ///
    /// # Panics
    /// If the range is out of bounds (like arrow's `slice`).
    #[must_use]
    pub fn slice(&self, offset: usize, length: usize) -> Self {
        Self {
            array: self.array.slice(offset, length),
            name: Arc::clone(&self.name),
            metadata: Arc::clone(&self.metadata),
        }
    }

    /// The data half of this column: the typed array, without the name or the
    /// metadata.
    #[must_use]
    pub fn as_typed_array(&self) -> &TypedArray<L> {
        &self.array
    }

    /// Discards the name and the metadata, keeping the typed array.
    ///
    /// The inverse of [`Column::new`].
    #[must_use]
    pub fn into_typed_array(self) -> TypedArray<L> {
        self.array
    }

    /// Forgets the static type: the same data, as a dynamically-typed column.
    ///
    /// The field carries this column's [`name`](Column::name) and
    /// [`metadata`](Column::metadata), the data type of the array, and the
    /// nullability of `L`. Zero-copy: the array is moved. To rename on the way
    /// out, go through [`with_name`](Column::with_name).
    ///
    /// Works for every logical type, the parse-only ones
    /// ([`AnyUtf8`](crate::AnyUtf8), [`AnyList`](crate::AnyList), …) included:
    /// the field's data type comes from the array, not from `L`.
    ///
    /// The inverse is [`DynColumn::try_into_column`](crate::DynColumn::try_into_column).
    #[must_use]
    pub fn into_dyn(self) -> crate::DynColumn {
        let Self {
            array,
            name,
            metadata,
        } = self;
        let array = array.into_arrow();

        // The array's own data type rather than `L::data_type()`: the two agree
        // on everything `L` pins down, but a validated array may still differ
        // in a detail the logical type does not constrain (the name of a list's
        // inner field, say) — and a `DynColumn`'s field must describe the array
        // it is paired with, exactly.
        let field = Field::new(name.as_str(), array.data_type().clone(), L::NULLABLE)
            .with_metadata(Arc::unwrap_or_clone(metadata).into_iter().collect());

        crate::DynColumn::new_unvalidated(Arc::new(field), array)
    }

    /// The same column, read as nullable: `Column<L>` → `Column<Option<L>>`.
    ///
    /// Free — nullability lives in the validity bitmap, so nothing is
    /// re-validated, copied, or re-downcast — and the name and metadata come
    /// along.
    ///
    /// Nullability is idempotent: an already-nullable column is its own
    /// `optional()`, so this never nests into `Option<Option<…>>`.
    /// [`try_required`](Column::try_required) goes the other way.
    ///
    /// ```
    /// # use quiver::Column;
    /// let ages = Column::<i64>::from_values("age", [30, 40]);
    /// let maybe: Column<Option<i64>> = ages.optional();
    /// assert_eq!(maybe.to_vec(), [Some(30), Some(40)]);
    /// ```
    #[must_use]
    #[doc(alias = "nullable")]
    pub fn optional(self) -> Column<L::Optional> {
        let Self {
            array,
            name,
            metadata,
        } = self;
        Column {
            array: array.optional(),
            name,
            metadata,
        }
    }

    /// The same column, read as non-nullable: `Column<Option<L>>` → `Column<L>`.
    ///
    /// The inverse of [`optional`](Column::optional), and fallible because the
    /// column may actually contain nulls. Every `Option` layer comes off, so
    /// this is idempotent too: an already-non-nullable column always converts.
    ///
    /// The name and metadata come along, and nothing is copied or re-downcast.
    ///
    /// ```
    /// # use quiver::Column;
    /// let ages = Column::<Option<i64>>::from_values("age", [Some(30), Some(40)]);
    /// assert_eq!(ages.try_required()?.to_vec(), [30, 40]);
    ///
    /// let with_null = Column::<Option<i64>>::from_values("age", [Some(30), None]);
    /// assert!(with_null.try_required().is_err());
    /// # Ok::<(), quiver::ColumnError>(())
    /// ```
    ///
    /// # Errors
    /// Errors with [`ColumnError::UnexpectedNulls`] if the column contains nulls.
    #[doc(alias = "non_nullable")]
    pub fn try_required(self) -> Result<Column<L::Required>, ColumnError> {
        let Self {
            array,
            name,
            metadata,
        } = self;
        Ok(Column {
            array: array.try_required()?,
            name,
            metadata,
        })
    }

    /// The underlying arrow array.
    #[must_use]
    pub fn as_arrow(&self) -> &ArrayRef {
        self.array.as_arrow()
    }

    /// Extract the underlying arrow array.
    #[must_use]
    pub fn into_arrow(self) -> ArrayRef {
        self.array.into_arrow()
    }
}

/// Construction and schema, for logical types with a single concrete arrow
/// data type. (Multi-encoding types like [`AnyList`](crate::AnyList) are
/// parse-only: build a concrete encoding instead.)
impl<L: crate::ConcreteType> Column<L> {
    /// Builds a column from owned values; the fallible form of
    /// [`Column::from_values`], needed only for fallible encodings
    /// (dictionary key overflow).
    ///
    /// # Errors
    /// Errors if the encoding fails, e.g. too many distinct values
    /// for the dictionary key type.
    pub fn try_from_values(
        name: impl Into<String>,
        values: impl IntoIterator<Item = impl Into<L::Owned>>,
    ) -> Result<Self, ColumnError> {
        Ok(Self::new(name, TypedArray::try_from_values(values)?))
    }

    /// An empty column of this data type.
    ///
    /// `Column` has no `Default`, since a column without a name is not a
    /// column; [`TypedArray`] is the type with the `Default` impl.
    #[must_use]
    pub fn empty(name: impl Into<String>) -> Self {
        Self::new(name, TypedArray::default())
    }

    /// The exact arrow data type of this column.
    #[must_use]
    pub fn data_type() -> DataType {
        L::data_type()
    }
}

/// `column[index]`: like [`Column::value`], but borrows from the array —
/// `&column[i]` is `&str` for a `Column<Utf8>`, `&i64` for a `Column<i64>`.
///
/// Available for columns whose values can be borrowed from the array:
/// strings, binaries, and primitives — but not `bool` (bit-packed),
/// nullable (`Option<…>`), or nested (`List<…>`) columns,
/// whose values are built on the fly.
///
/// Panics if out of bounds (like [`Column::value`]).
///
/// ```
/// # use quiver::{Column, Utf8};
/// let strings = Column::<Utf8>::from_values("word", ["a", "b"]);
/// assert_eq!(&strings[1], "b");
///
/// let numbers = Column::<i64>::from_values("number", [1, 2, 3]);
/// assert_eq!(numbers[2], 3);
/// ```
impl<L: RefType> std::ops::Index<usize> for Column<L> {
    type Output = L::Ref;

    fn index(&self, index: usize) -> &Self::Output {
        &self.array[index]
    }
}

impl<L: PrimitiveType> Column<L> {
    /// The values as a contiguous zero-copy slice,
    /// e.g. `&[f32]` for a `Column<f32>`,
    /// or `&[[u8; 16]]` for a `Column<FixedSizeBinary<16>>`.
    ///
    /// Only available for primitive and fixed-size binary non-nullable columns
    /// (`bool` is excluded: arrow bit-packs it).
    ///
    /// A newtype declared with the `primitive` arm of
    /// [`newtype_data_type!`](crate::newtype_data_type) yields the newtype itself
    /// (`&[Uuid]`, not `&[[u8; 16]]`).
    ///
    /// ```
    /// # use quiver::{Column, FixedSizeBinary};
    /// let column = Column::<f32>::from_values("weight", [1.0, 2.0, 3.0]);
    /// assert_eq!(column.as_slice(), &[1.0, 2.0, 3.0]);
    ///
    /// let hashes =
    ///     Column::<FixedSizeBinary<4>>::from_values("hash", [[1, 2, 3, 4], [5, 6, 7, 8]]);
    /// assert_eq!(hashes.as_slice(), &[[1, 2, 3, 4], [5, 6, 7, 8]]);
    /// ```
    #[must_use]
    pub fn as_slice(&self) -> &[L::Native] {
        self.array.as_slice()
    }
}

/// `&column` where `&[L::Native]` is expected, for the same columns as
/// [`as_slice`](Column::as_slice) — so a `Column<u64>` is a drop-in for the
/// `ScalarBuffer<u64>` it replaces:
///
/// ```
/// # use quiver::Column;
/// struct Manifest {
///     chunk_byte_sizes: Column<u64>, // was: ScalarBuffer<u64>
/// }
///
/// impl Manifest {
///     fn chunk_byte_sizes(&self) -> &[u64] {
///         &self.chunk_byte_sizes // unchanged
///     }
/// }
/// # let manifest = Manifest {
/// #     chunk_byte_sizes: Column::from_values("chunk_byte_sizes", [1_u64, 2]),
/// # };
/// # assert_eq!(manifest.chunk_byte_sizes(), &[1, 2]);
/// ```
///
/// The slice methods come along, but never displace `Column`'s own: an
/// inherent method wins over a dereferenced one, so `iter`, `len`, `get`,
/// and `to_vec` still read the column, not the raw slice. Indexing likewise
/// stays with `Index<usize>`, so range slicing needs an explicit
/// `&(*column)[a..b]`.
///
/// Rule: `Column` never gains an inherent method that `[T]` already has.
/// An inherent `first()` would silently change what every existing
/// `column.first()` call site returns. The `deref_to_slice` test pins those
/// names, so CI catches it.
impl<L: PrimitiveType> std::ops::Deref for Column<L> {
    type Target = [L::Native];

    #[inline]
    fn deref(&self) -> &Self::Target {
        self.as_slice()
    }
}

/// The generic counterpart of [`Column::as_slice`], for callers bounded on
/// `AsRef<[T]>`.
impl<L: PrimitiveType> AsRef<[L::Native]> for Column<L> {
    #[inline]
    fn as_ref(&self) -> &[L::Native] {
        self.as_slice()
    }
}

impl<L: LogicalType> Column<L>
where
    L: InfallibleBuild,
{
    /// Builds a column from owned values,
    /// e.g. `Column::<Utf8>::from_values("sensor", ["a", "b"])`.
    ///
    /// Infallible — for the one fallible encoding (dictionaries),
    /// see [`Column::try_from_values`].
    ///
    /// # Panics
    /// Never: the logical type is [`InfallibleBuild`].
    pub fn from_values(
        name: impl Into<String>,
        values: impl IntoIterator<Item = impl Into<L::Owned>>,
    ) -> Self {
        Self::new(name, TypedArray::from_values(values))
    }
}

impl<L: crate::ConcreteType> Column<Option<L>> {
    /// Builds a nullable column from optional values; the fallible form of
    /// [`Column::from_nullable_values`].
    ///
    /// # Errors
    /// Errors if the encoding fails, e.g. too many distinct values
    /// for the dictionary key type.
    pub fn try_from_nullable_values(
        name: impl Into<String>,
        values: impl IntoIterator<Item = Option<impl Into<L::Owned>>>,
    ) -> Result<Self, ColumnError> {
        Self::try_from_values(name, values.into_iter().map(|value| value.map(Into::into)))
    }
}

impl<L: crate::ConcreteType> Column<Option<L>> {
    /// A column of `len` nulls, with no metadata.
    ///
    /// The direct way to pad a record batch that is missing a column, without
    /// naming a value type the column never holds — spelling out
    /// `from_nullable_values(std::iter::repeat_n(None::<Vec<u8>>, len))` just
    /// to satisfy inference — and cheaper than building through the values.
    ///
    /// ```
    /// # use quiver::{Binary, Column};
    /// let keys = Column::<Option<Binary>>::new_null("chunk_key", 3);
    /// assert_eq!(keys.len(), 3);
    /// assert_eq!(keys.to_vec(), [None, None, None]);
    /// ```
    ///
    /// # Panics
    /// Panics for run-end encoding, at any `len`: a `RunArray` has no validity
    /// buffer of its own, so its nulls live in the values —
    /// `Run<K, Option<V>>`, not `Option<Run<K, V>>`. That spelling is still
    /// *reachable*, through [`optional`](Column::optional); see
    /// [`Run`](crate::Run) for what it reads as.
    #[must_use]
    pub fn new_null(name: impl Into<String>, len: usize) -> Self {
        Self::new(name, TypedArray::<Option<L>>::new_null(len))
    }
}

impl<L: InfallibleBuild> Column<Option<L>> {
    /// Builds a nullable column from optional values.
    ///
    /// Unlike [`Column::from_values`], the values inside the `Option`s may still
    /// need converting, e.g. `Option<&str>` for a `Column<Option<Utf8>>`:
    ///
    /// ```
    /// # use quiver::{Column, Utf8};
    /// let column = Column::<Option<Utf8>>::from_nullable_values("name", [Some("a"), None]);
    /// ```
    pub fn from_nullable_values(
        name: impl Into<String>,
        values: impl IntoIterator<Item = Option<impl Into<L::Owned>>>,
    ) -> Self {
        Self::from_values(name, values.into_iter().map(|value| value.map(Into::into)))
    }
}

/// Compares the name, the data (like arrow array equality), and the metadata.
impl<L: LogicalType> PartialEq for Column<L> {
    fn eq(&self, other: &Self) -> bool {
        let Self {
            array,
            name,
            metadata,
        } = self;
        *name == other.name && *metadata == other.metadata && *array == other.array
    }
}

impl<L: LogicalType> Clone for Column<L> {
    fn clone(&self) -> Self {
        Self {
            array: self.array.clone(),
            name: Arc::clone(&self.name),
            metadata: Arc::clone(&self.metadata),
        }
    }
}

impl<L: LogicalType> std::fmt::Debug for Column<L> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Column")
            .field("name", &self.name)
            .field("array", self.array.as_arrow())
            .field("metadata", &self.metadata)
            .finish_non_exhaustive()
    }
}

impl<'a, L: LogicalType + 'a> IntoIterator for &'a Column<L> {
    type Item = L::Value<'a>;
    type IntoIter = TypedArrayIter<'a, L>;

    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

/// The old name of [`TypedArrayIter`], the iterator [`Column::iter`] returns.
#[deprecated(since = "0.6.0", note = "Renamed `TypedArrayIter`")]
pub type ColumnIter<'a, L> = TypedArrayIter<'a, L>;

/// The old name of [`TypedArrayIntoIter`], the iterator
/// [`Column::into_iter_owned`] returns.
#[deprecated(since = "0.6.0", note = "Renamed `TypedArrayIntoIter`")]
pub type ColumnIntoIter<L> = TypedArrayIntoIter<L>;
