//! [`Column<L>`]: a strongly-typed, validated, zero-copy view of one record batch column.
//!
//! The wrapper validates the arrow array **once, eagerly** at construction
//! (exact datatype, including the inner types of nested arrays, plus nulls at
//! every non-`Option` nesting level). After that, element access is infallible,
//! fully typed, and zero-copy.

use arrow::array::ArrayRef;
use arrow::datatypes::{DataType, Field};

use crate::datatype::{InfallibleBuild, PrimitiveType, RefType};
use crate::typed_array::{TypedArray, TypedArrayIntoIter, TypedArrayIter};
use crate::{ColumnError, Error, ErrorKind, LogicalType};

/// A strongly-typed, validated, zero-copy view of one record batch column.
///
/// The logical type `L` describes the exact datatype and nullability,
/// e.g. `Column<List<Utf8>>` or `Column<Option<i64>>`.
///
/// # Relationship to the other main types
/// A column is a [`TypedArray<L>`](TypedArray) (the validated array, and every
/// method for reading it) plus the per-column [`metadata`](Column::metadata)
/// that lives on the arrow [`Field`]. Use a
/// [`TypedArray`] instead for an array that isn't a record batch column, and so
/// has no metadata to carry; convert either way with
/// [`as_typed_array`](Column::as_typed_array),
/// [`into_typed_array`](Column::into_typed_array), and `Column::from`.
///
/// Getting a column out of a record batch by name is
/// [`Column::from_record_batch_and_name`], or a
/// [`ColumnDesc`](crate::ColumnDesc) — generated by `#[derive(Quiver)]`, or
/// declared by you — which holds the name and `L` so the call site needs
/// neither.
pub struct Column<L: LogicalType> {
    /// The data: the arrow array plus its downcast view.
    array: TypedArray<L>,

    /// Per-column metadata, stored on the arrow [`arrow::datatypes::Field`]
    /// when converting to/from a record batch.
    metadata: std::collections::BTreeMap<String, String>,
}

impl<L: LogicalType> Column<L> {
    /// May the values of this column be null?
    pub const NULLABLE: bool = L::NULLABLE;

    /// Validates the array against the logical type `L` (datatype and nullability,
    /// recursively), then downcasts it (zero-copy).
    ///
    /// # Errors
    /// Errors on datatype mismatch, or on nulls at any non-`Option` nesting level.
    pub fn try_new(array: ArrayRef) -> Result<Self, ColumnError> {
        Ok(Self {
            array: TypedArray::try_new(array)?,
            metadata: std::collections::BTreeMap::new(),
        })
    }

    /// Extracts and validates a single column of a record batch, by name.
    ///
    /// Looks up the column by name (returning [`ErrorKind::MissingColumn`] if it
    /// is absent), validates it against `L` (datatype and nullability, recursively),
    /// and carries over the arrow [`Field`] metadata.
    ///
    /// This is the no-derive equivalent of the `COLUMN_*` descriptors that
    /// `#[derive(Quiver)]` generates; prefer those when you have a derived struct,
    /// since they don't hard-code the column name.
    ///
    /// # Errors
    /// Errors if the column is missing, or if it fails validation against `L`.
    pub fn from_record_batch_and_name(
        batch: &arrow::record_batch::RecordBatch,
        name: &str,
    ) -> Result<Self, Error> {
        Self::extract_named(batch, name, "Column")
    }

    /// Shared implementation of [`Column::from_record_batch_and_name`] and the
    /// derive-generated `COLUMN_*` descriptors; `record_type` labels errors.
    pub(crate) fn extract_named(
        batch: &arrow::record_batch::RecordBatch,
        name: &str,
        record_type: &'static str,
    ) -> Result<Self, Error> {
        let (index, field) = batch.schema_ref().column_with_name(name).ok_or_else(|| {
            Error::new(
                record_type,
                ErrorKind::MissingColumn {
                    column: name.to_owned(),
                },
            )
        })?;

        let column = Self::try_new(ArrayRef::clone(batch.column(index)))
            .map_err(|err| Error::new(record_type, err.for_column(name.to_owned())))?;

        Ok(column.with_metadata(
            field
                .metadata()
                .iter()
                .map(|(key, value)| (key.clone(), value.clone()))
                .collect(),
        ))
    }

    /// Per-column metadata, stored on the arrow [`arrow::datatypes::Field`]
    /// when converting to/from a record batch.
    #[must_use]
    pub fn metadata(&self) -> &std::collections::BTreeMap<String, String> {
        &self.metadata
    }

    /// Mutable access to the per-column metadata; see [`Column::metadata`].
    pub fn metadata_mut(&mut self) -> &mut std::collections::BTreeMap<String, String> {
        &mut self.metadata
    }

    /// Replace the per-column metadata.
    #[must_use]
    pub fn with_metadata(mut self, metadata: std::collections::BTreeMap<String, String>) -> Self {
        self.metadata = metadata;
        self
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.array.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.array.is_empty()
    }

    /// The value at `index`, or `None` if out of bounds.
    ///
    /// See [`Column::value`] for the returned view;
    /// [`Column::get_owned`] returns the owned value instead.
    #[must_use]
    #[inline]
    pub fn get(&self, index: usize) -> Option<L::Value<'_>> {
        self.array.get(index)
    }

    /// The owned value at `index`, or `None` if out of bounds —
    /// e.g. `String` (or your newtype) where [`Column::get`] returns `&str`.
    #[must_use]
    pub fn get_owned(&self, index: usize) -> Option<L::Owned> {
        self.get(index).map(L::to_owned_value)
    }

    /// The value at `index`.
    ///
    /// Works for every logical type, returning the zero-copy view
    /// ([`LogicalType::Value`]): `&str`, `i64`, `Option<…>`, an iterator for
    /// `List<…>`, etc.
    /// Where a plain reference exists in the array — strings, binaries,
    /// primitives (but not `bool`, `Option<…>`, or `List<…>`) — `column[index]`
    /// works too, and is handy with generic code expecting `&T`.
    /// For the owned value (e.g. `String`, or your `newtype_datatype!` type),
    /// see [`Column::value_owned`].
    ///
    /// Panics if out of bounds.
    #[must_use]
    #[inline]
    pub fn value(&self, index: usize) -> L::Value<'_> {
        self.array.value(index)
    }

    /// The owned value at `index` — e.g. `String` (or your newtype)
    /// where [`Column::value`] returns `&str`.
    ///
    /// May allocate (e.g. string columns); for bulk access,
    /// prefer [`Column::iter_owned`] or [`Column::to_vec`].
    ///
    /// Panics if out of bounds.
    #[must_use]
    pub fn value_owned(&self, index: usize) -> L::Owned {
        L::to_owned_value(self.value(index))
    }

    /// Iterates over the zero-copy views ([`LogicalType::Value`]):
    /// `&str`, `i64`, etc — like [`Column::value`], element by element.
    ///
    /// For owned values, see [`Column::iter_owned`].
    #[must_use]
    pub fn iter(&self) -> TypedArrayIter<'_, L> {
        self.array.iter()
    }

    /// Iterates over owned values — e.g. `String` (or your newtype)
    /// where [`Column::iter`] yields `&str`.
    ///
    /// May allocate per element (e.g. string columns).
    pub fn iter_owned(&self) -> impl Iterator<Item = L::Owned> + '_ {
        self.array.iter_owned()
    }

    /// Consumes the column, iterating over owned values — e.g. `String`
    /// (or your newtype) for a `Column<Utf8>`.
    ///
    /// May allocate per element (e.g. string columns); for borrowed views,
    /// iterate `&column` (or call [`Column::iter`]) instead.
    #[must_use]
    pub fn into_iter_owned(self) -> TypedArrayIntoIter<L> {
        self.array.into_iter_owned()
    }

    /// Copies the values into a `Vec` of owned values,
    /// e.g. `Vec<String>` for a `Column<Utf8>`.
    #[must_use]
    pub fn to_vec(&self) -> Vec<L::Owned> {
        self.array.to_vec()
    }

    /// A zero-copy slice of the rows `offset..offset + length`.
    ///
    /// The metadata is preserved.
    ///
    /// # Panics
    /// If the range is out of bounds (like arrow's `slice`).
    #[must_use]
    pub fn slice(&self, offset: usize, length: usize) -> Self {
        Self {
            array: self.array.slice(offset, length),
            metadata: self.metadata.clone(),
        }
    }

    /// The data half of this column: the typed array, without the metadata.
    #[must_use]
    pub fn as_typed_array(&self) -> &TypedArray<L> {
        &self.array
    }

    /// Discards the metadata, keeping the typed array.
    #[must_use]
    pub fn into_typed_array(self) -> TypedArray<L> {
        self.array
    }

    /// The underlying arrow array.
    #[must_use]
    pub fn as_arrow(&self) -> &ArrayRef {
        self.array.as_arrow()
    }

    /// Extract the underlying arrow array.
    #[must_use]
    pub fn into_arrow(self) -> ArrayRef {
        self.array.into_arrow()
    }
}

/// Construction and schema, for logical types with a single concrete arrow
/// datatype. (Multi-encoding types like [`AnyList`](crate::AnyList) are
/// parse-only: build a concrete encoding instead.)
impl<L: crate::ConcreteType> Column<L> {
    /// Builds a column from owned values; the fallible form of
    /// [`Column::from_values`], needed only for fallible encodings
    /// (dictionary key overflow).
    ///
    /// # Errors
    /// Errors if the encoding fails, e.g. too many distinct values
    /// for the dictionary key type.
    pub fn try_from_values(
        values: impl IntoIterator<Item = impl Into<L::Owned>>,
    ) -> Result<Self, ColumnError> {
        let array = L::build(values.into_iter().map(|value| Some(value.into())))?;
        Self::try_new(array)
    }

    /// The exact arrow datatype of this column.
    #[must_use]
    pub fn datatype() -> DataType {
        L::datatype()
    }

    /// Forgets the static type: the same data, as a dynamically-typed column
    /// whose arrow field is called `column_name`.
    ///
    /// The field carries the datatype and nullability of `L`, plus this
    /// column's [`metadata`](Column::metadata). Zero-copy: the array is moved.
    ///
    /// The inverse is [`DynColumn::try_into_column`](crate::DynColumn::try_into_column).
    #[must_use]
    pub fn into_dyn(self, column_name: impl Into<String>) -> crate::DynColumn {
        let Self { array, metadata } = self;
        crate::DynColumn {
            field: std::sync::Arc::new(
                Field::new(column_name, L::datatype(), L::NULLABLE)
                    .with_metadata(metadata.into_iter().collect()),
            ),
            array: array.into_arrow(),
        }
    }
}

/// `column[index]`: like [`Column::value`], but borrows from the array —
/// `&column[i]` is `&str` for a `Column<Utf8>`, `&i64` for a `Column<i64>`.
///
/// Available for columns whose values can be borrowed from the array:
/// strings, binaries, and primitives — but not `bool` (bit-packed),
/// nullable (`Option<…>`), or nested (`List<…>`) columns,
/// whose values are built on the fly.
///
/// Panics if out of bounds (like [`Column::value`]).
///
/// ```
/// # use quiver::{Column, Utf8};
/// let strings = Column::<Utf8>::from_values(["a", "b"]);
/// assert_eq!(&strings[1], "b");
///
/// let numbers = Column::<i64>::from_values([1, 2, 3]);
/// assert_eq!(numbers[2], 3);
/// ```
impl<L: RefType> std::ops::Index<usize> for Column<L> {
    type Output = L::Ref;

    fn index(&self, index: usize) -> &Self::Output {
        &self.array[index]
    }
}

impl<L: PrimitiveType> Column<L> {
    /// The values as a contiguous zero-copy slice,
    /// e.g. `&[f32]` for a `Column<f32>`,
    /// or `&[[u8; 16]]` for a `Column<FixedSizeBinary<16>>`.
    ///
    /// Only available for primitive and fixed-size binary non-nullable columns
    /// (`bool` is excluded: arrow bit-packs it).
    ///
    /// ```
    /// # use quiver::{Column, FixedSizeBinary};
    /// let column = Column::<f32>::from_values([1.0, 2.0, 3.0]);
    /// assert_eq!(column.as_slice(), &[1.0, 2.0, 3.0]);
    ///
    /// let hashes = Column::<FixedSizeBinary<4>>::from_values([[1, 2, 3, 4], [5, 6, 7, 8]]);
    /// assert_eq!(hashes.as_slice(), &[[1, 2, 3, 4], [5, 6, 7, 8]]);
    /// ```
    #[must_use]
    pub fn as_slice(&self) -> &[L::Native] {
        self.array.as_slice()
    }
}

impl<L: LogicalType> Column<L>
where
    L: InfallibleBuild,
{
    /// Builds a column from owned values,
    /// e.g. `Column::<Utf8>::from_values(["a", "b"])`.
    ///
    /// Infallible — for the one fallible encoding (dictionaries),
    /// see [`Column::try_from_values`].
    ///
    /// # Panics
    /// Never: the logical type is [`InfallibleBuild`].
    pub fn from_values(values: impl IntoIterator<Item = impl Into<L::Owned>>) -> Self {
        Self::try_from_values(values).expect("Cannot fail: the logical type is InfallibleBuild")
    }
}

impl<L: crate::ConcreteType> Column<Option<L>> {
    /// Builds a nullable column from optional values; the fallible form of
    /// [`Column::from_nullable_values`].
    ///
    /// # Errors
    /// Errors if the encoding fails, e.g. too many distinct values
    /// for the dictionary key type.
    pub fn try_from_nullable_values(
        values: impl IntoIterator<Item = Option<impl Into<L::Owned>>>,
    ) -> Result<Self, ColumnError> {
        Self::try_from_values(values.into_iter().map(|value| value.map(Into::into)))
    }
}

impl<L: InfallibleBuild> Column<Option<L>> {
    /// Builds a nullable column from optional values.
    ///
    /// Unlike [`Column::from_values`], the values inside the `Option`s may still
    /// need converting, e.g. `Option<&str>` for a `Column<Option<Utf8>>`:
    ///
    /// ```
    /// # use quiver::{Column, Utf8};
    /// let column = Column::<Option<Utf8>>::from_nullable_values([Some("a"), None]);
    /// ```
    pub fn from_nullable_values(
        values: impl IntoIterator<Item = Option<impl Into<L::Owned>>>,
    ) -> Self {
        Self::from_values(values.into_iter().map(|value| value.map(Into::into)))
    }
}

impl<L: InfallibleBuild, T: Into<L::Owned>> From<Vec<T>> for Column<L> {
    fn from(values: Vec<T>) -> Self {
        Self::from_values(values)
    }
}

impl<L: InfallibleBuild, T: Into<L::Owned>> FromIterator<T> for Column<L> {
    fn from_iter<I: IntoIterator<Item = T>>(values: I) -> Self {
        Self::from_values(values)
    }
}

/// An empty column. Only for logical types with a single concrete datatype.
impl<L: crate::ConcreteType> Default for Column<L> {
    fn default() -> Self {
        let array = arrow::array::new_empty_array(&L::datatype());
        Self::try_new(array).expect("An empty array of the right datatype is always valid")
    }
}

/// Compares the data (like arrow array equality) and the metadata.
impl<L: LogicalType> PartialEq for Column<L> {
    fn eq(&self, other: &Self) -> bool {
        self.metadata == other.metadata && self.array == other.array
    }
}

impl<L: LogicalType> Clone for Column<L> {
    fn clone(&self) -> Self {
        Self {
            array: self.array.clone(),
            metadata: self.metadata.clone(),
        }
    }
}

impl<L: LogicalType> std::fmt::Debug for Column<L> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Column")
            .field("array", self.array.as_arrow())
            .field("metadata", &self.metadata)
            .finish_non_exhaustive()
    }
}

impl<L: LogicalType> TryFrom<ArrayRef> for Column<L> {
    type Error = ColumnError;

    fn try_from(array: ArrayRef) -> Result<Self, Self::Error> {
        Self::try_new(array)
    }
}

/// A typed array becomes a column with no metadata.
impl<L: LogicalType> From<TypedArray<L>> for Column<L> {
    fn from(array: TypedArray<L>) -> Self {
        Self {
            array,
            metadata: std::collections::BTreeMap::new(),
        }
    }
}

impl<'a, L: LogicalType + 'a> IntoIterator for &'a Column<L> {
    type Item = L::Value<'a>;
    type IntoIter = TypedArrayIter<'a, L>;

    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

/// The old name of [`TypedArrayIter`], the iterator [`Column::iter`] returns.
#[deprecated(since = "0.6.0", note = "Renamed `TypedArrayIter`")]
pub type ColumnIter<'a, L> = TypedArrayIter<'a, L>;

/// The old name of [`TypedArrayIntoIter`], the iterator
/// [`Column::into_iter_owned`] returns.
#[deprecated(since = "0.6.0", note = "Renamed `TypedArrayIntoIter`")]
pub type ColumnIntoIter<L> = TypedArrayIntoIter<L>;
